<a href="https://colab.research.google.com/github/Nithya-Satheesh/LETS_UPGRADE_ASSIGNMENT3/blob/main/LETS_UPGRADE3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question 1
import numpy as np
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [ ]:
#Question 2
import numpy as np
list1 = []
list2 = []
for i in range(5):
 ele = int(input("Enter a number for list1: "))
 list1.append(ele)
for i in range(5):
 ele = int(input("Enter a number for list2: "))
 list2.append(ele)

arr1 = np.array(list1)
arr2 = np.array(list2)

arr = np.concatenate((arr1,arr2))
print("Concatenated array: ",arr)

sort = np.sort(arr)
print("Sorted: ",sort)


Enter a number for list1: 12
Enter a number for list1: 43
Enter a number for list1: 77
Enter a number for list1: 98
Enter a number for list1: 7
Enter a number for list2: 4
Enter a number for list2: 54
Enter a number for list2: 43
Enter a number for list2: 22
Enter a number for list2: 66
Concatenated array:  [12 43 77 98  7  4 54 43 22 66]
Sorted:  [ 4  7 12 22 43 43 54 66 77 98]


**Snippets**

Dimension 

Array_Name.ndim

Size

Array_Name.size

In [ ]:
#Question 3
import numpy as np
arr = np.array([[1,4,5],[22,4,3]])
Dim = arr.ndim
print("Dimension of the array: ",Dim)
Size = arr.size
print("size of array: ",Size)

Dimension of the array:  2
size of array:  6


newaxis snippet:

ArrayName[numpy.newaxis, :] // row major

ArrayName[:, numpy.newaxis] // column major

In [6]:
#Question 4
import numpy as np
a = np.array([1,3,6,8,4,9])
print(a.shape)
row_vector = a[np.newaxis, :]
col_vector = a[:, np.newaxis]
print(row_vector.shape)
print(col_vector.shape)

(6,)
(1, 6)
(6, 1)


In [10]:
#Question 5
import numpy as np
a1 = [23,32,1,22,35]
a2 = [73,43,23,55,66]
s1 = np.square(a1)
s2 = np.square(a2)

print("Vertical stack: ", np.vstack((s1,s2)))
print("Horizontal stack: ",np.hstack((s1,s2)))

Vertical stack:  [[ 529 1024    1  484 1225]
 [5329 1849  529 3025 4356]]
Horizontal stack:  [ 529 1024    1  484 1225 5329 1849  529 3025 4356]


In [12]:
#Question 6
import numpy as np

a1 = np.array([1,3,4,2,5,1,2,3,9])
(unique, counts) = np.unique(a1, return_counts=True)

a = np.asarray((unique,counts)).T
print(a)

[[1 2]
 [2 2]
 [3 2]
 [4 1]
 [5 1]
 [9 1]]
